### ISSUE TITLE
Where is the project at ?

### ISSUE THREAD

**Issue by raed667** [ClubEspritLibre/the-Gnu-Distro#18]
ayn antom?

**Comment by rednaks** [comment]
at what ?

**Comment by raed667** [comment]
at home  u_u 

is it operational ?

**Comment by rednaks** [comment]
Yes it is, but if you create a bootable usb disk you can't reverse it ... you have to do it manually with gparted

**Comment by raed667** [comment]
reversing it was never part of the specs  ! :)

**Comment by rednaks** [comment]
yeah but it would be nice if you can work on it :D, just open a new issue describing what you are going to do.

**Comment by rednaks** [comment]
@asmasma21  You can maybe mentor him ?

**Comment by asmasma21** [comment]
@Raed667 you need help ? :3

**Comment by raed667** [comment]
do i look like i have time ? :p .. next year .. maybe

**Comment by asmasma21** [comment]
@Raed667 see you next year :3

**Comment by rednaks** [comment]
Fine, then i'm closing the issue :)

**Comment by raed667** [comment]
Darn you !
